# This is a config file to edit parameters of the pipeline and 
# the pipeline's rules

# Global Parameters
blacklist_file:     'resources/hg38-blacklist.v2.bed'
genome_fasta:       'resources/GRCh38.primary_assembly.genome.fa.gz'
genome_fasta_unzip: 'resources/GRCh38.primary_assembly.genome.fa'
genome_annotation:  'resources/gencode.v45.primary_assembly.annotation.gtf'

# Trimmomatic Parameters for raw read trimming and quality control
trimmomatic:
    # Specify Read Type (paired end not actually implemented)
    read_type:      'PE'

    # Path to fasta file containing adapter sequences to remove in raw sequencing reads
    adapter_file:   '/projectnb/bf528/materials/project_2_chipseq/TruSeq3-SE.fa'

    # Quality score metric 
    quality_score:  '-phred33'

    # Basepair filtering by position and quality
    leading:        'LEADING:3'
    trailing:       'TRAILING:3'
    slidingwindow:  'SLIDINGWINDOW:4:15'
    illuminaclip:   '2:30:10' 


# Bowtie 2 parameters for genome building and aligning
bowtie2:
    # Directory to put index into
    index_folder:       'resources/GRCh38_index'

    # Index Path: includes reference to index for bowtie
    index_path:         'resources/GRCh38_index/GRCh38'  

    # (BUILD): name of index to build
    index_name:         'GRCh38'

    # (ALIGN): Maximum fragment length 
    max_frag_length:    '2000'


# DeepTools parameters for alignment processing
deeptools:
    ### ALIGNMENT SIEVE PARAMETERS FOR ALL NUCLEOSOME BOUND STATUS
    all:
        # (ALIGNMENT SIEVE) Minimum and maximum fragment length needed for read/pair inclusions for filtering for NFR
        minFragmentLength:  '0'
        maxFragmentLength:  '0'

    nfr:
        # (ALIGNMENT SIEVE) Minimum and maximum fragment length needed for read/pair inclusions for filtering for NFR
        minFragmentLength:  '0'
        maxFragmentLength:  '100'

    mono:
        # (ALIGNMENT SIEVE) Minimum and maximum fragment length needed for read/pair inclusions for filtering for Mononucleosomes
        minFragmentLength:  '180'
        maxFragmentLength:  '247'

    di:
        # (ALIGNMENT SIEVE) Minimum and maximum fragment length needed for read/pair inclusions for filtering for Dinucleosomes
        minFragmentLength:  '315'
        maxFragmentLength:  '473'

    ### Compute Matrix parameter for how far (in basepairs) to scan up and downstream the point of interest
    up_down_stream: '1000'


# Bedtools parameters for intersecting peaks
bedtools:
    # Intersect Overlap Requirement
    overlap: '0.5'

# HOMER rule parameters 
homer:
    # Region size for motif analysis
    motif_region_size: '300'
